{{- if .Values.application.email.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Chart.Name }}{{ .Values.environment.suffix }}-email-secret
  labels:
    app: {{ .Chart.Name }}{{ .Values.environment.suffix }}
type: Opaque
stringData:
  EMAIL_PASSWORD: {{ .Values.application.email.password | quote }}
{{- end }}
