name: Publish Docker Images

on:
  workflow_dispatch:
    inputs:
      registry:
        description: 'Docker registry (e.g., docker.io, ghcr.io)'
        required: true
        default: 'ghcr.io'
        type: choice
        options:
          - docker.io
          - ghcr.io
      image-tag:
        description: 'Additional tag (e.g., latest, stable, v1.0.0)'
        required: false
        default: 'latest'
        type: string

jobs:
  publish-docker-images:
    permissions:
      contents: read
      packages: write
    uses: ./.github/workflows/docker-build.yml
    with:
      push-to-registry: true
      registry: ${{ inputs.registry }}
      image-tag: ${{ inputs.image-tag }}
    secrets:
      registry-username: ${{ inputs.registry == 'ghcr.io' && github.actor || secrets.DOCKER_USERNAME }}
      registry-password: ${{ inputs.registry == 'ghcr.io' && secrets.GITHUB_TOKEN || secrets.DOCKER_PASSWORD }}
